# Azure Web Apps Deployment Workflow using "Run From Package"
name: Build and deploy using Azure Run From Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        env:
          DATABASE_URL: postgresql://user:pass@localhost:5432/db?schema=public
        run: npm ci

      - name: Generate Prisma Client
        env:
          DATABASE_URL: postgresql://user:pass@localhost:5432/db?schema=public
        run: npx prisma generate

      - name: Build the app
        run: npm run build

      - name: Validate build output
        run: |
          if [ ! -f ./dist/server.js ]; then
            echo "Error: dist/server.js not found! Exiting..."
            exit 1
          fi

      - name: Create deployment zip
        run: |
          echo "Creating deployment package..."
          zip -r node-app.zip \
          ./dist \
          ./package.json \
          ./package-lock.json \
          ./tsconfig.json \
          ./prisma

      - name: Debug zip content
        run: |
          echo "Listing deployment package content:"
          unzip -l node-app.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Debug zip file
        run: |
          echo "Listing deployment package content:"
          unzip -l node-app.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AD46A304E9B94CD8AAC32DA788591380 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DFAA635A7AE6484AA3B606C8BD371009 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3054C42635F849958C5EFC095736A740 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TimesheetsAPI'
          slot-name: 'Production'
          package: node-app.zip