# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - TimesheetsAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Log Deployment Files
        run: |
          echo "Verifying node_modules..."
          ls -l node_modules/fastify || echo "Fastify module is missing!"
          ls -l node_modules/@prisma/client || echo "Prisma Client module is missing!"
          echo "Listing dist folder contents..."
          ls -l dist

      - name: Compress node_modules
        run: |
          tar -czf node_modules.tar.gz node_modules

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            ./dist
            ./src
            ./node_modules
            ./package.json
            ./package-lock.json
            ./prisma/schema.prisma
            ./prisma/prisma.config.ts

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AD46A304E9B94CD8AAC32DA788591380 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DFAA635A7AE6484AA3B606C8BD371009 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3054C42635F849958C5EFC095736A740 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TimesheetsAPI'
          slot-name: 'Production'
          package: .

      - name: Extract node_modules
        run: |
          cd /home/site/wwwroot
          mkdir -p node_modules
          tar -xzf node_modules.tar.gz -C node_modules