# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - TimesheetsAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      - name: Install Dependencies
        run: npm ci

      - name: Build the app
        run: npm run build # Replace this with your build command, if different

      - name: Generate Prisma Client
        env:
          NODE_ENV: production
          DATABASE_URL: "postgresql://placeholder" # Temporary placeholder for prisma generate
        run: npx prisma generate

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./dist # Replace ./dist with your actual build output folder

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./dist # Replace with the correct path to your build output (e.g., ./build or ./out)

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app # Matches the name used in the upload artifact step
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AD46A304E9B94CD8AAC32DA788591380 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DFAA635A7AE6484AA3B606C8BD371009 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3054C42635F849958C5EFC095736A740 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TimesheetsAPI'
          slot-name: 'Production'
          package: ./dist # Replace this with the location of the downloaded artifact